"""
Django settings for skills project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import json
import os
from pathlib import Path

import dj_database_url
from django.urls import reverse_lazy
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if not "SECRET_KEY" in os.environ:
    raise "No SECRET_KEY environment variable provided."

SECRET_KEY = os.environ.get("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [os.environ.get("APPLICATION_HOST")]

# Application definition

INSTALLED_APPS = [
                     "django.contrib.admin",
                     "django.contrib.auth",
                     "django.contrib.contenttypes",
                     "django.contrib.sessions",
                     "django.contrib.messages",
                     "django.contrib.staticfiles",
                     "skillsManager",
                     "auditlog",
                     "django_fastdev",
                     "markdownify.apps.MarkdownifyConfig",
                     "iommi",
                 ] + (
                     ["azure_auth"] if os.environ.get("AZURE_ENABLED", "false").lower() == "true" else []
                 )

MIDDLEWARE = [
                 "django.middleware.security.SecurityMiddleware",
                 "whitenoise.middleware.WhiteNoiseMiddleware",
                 "django.contrib.sessions.middleware.SessionMiddleware",
                 "django.middleware.locale.LocaleMiddleware",
                 "django.middleware.common.CommonMiddleware",
                 "django.middleware.csrf.CsrfViewMiddleware",
                 "django.contrib.auth.middleware.AuthenticationMiddleware",
                 "django.contrib.messages.middleware.MessageMiddleware",
                 "django.middleware.clickjacking.XFrameOptionsMiddleware",
                 "auditlog.middleware.AuditlogMiddleware",
                 "iommi.live_edit.Middleware",
                 "iommi.sql_trace.Middleware",
                 "iommi.profiling.Middleware",
                 "iommi.main_menu.main_menu_middleware",
                 "iommi.middleware",
             ] + (
                 ["azure_auth.middleware.AzureMiddleware"]
                 if os.environ.get("AZURE_ENABLED", "false").lower() == "true"
                 else ["skillsManager.middleware.auth.AuthMiddleware"]
             )

ROOT_URLCONF = "skills.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "skills.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///%s/db.sqlite3" % (BASE_DIR),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "static"
MEDIA_ROOT = BASE_DIR / "static/images"
MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AZURE_AUTH = {
    "CLIENT_ID": os.environ.get("AZURE_CLIENT_ID", ""),
    "CLIENT_SECRET": os.environ.get("AZURE_CLIENT_SECRET", ""),
    "REDIRECT_URI": reverse_lazy("azure_auth:callback"),
    "SCOPES": ["User.Read"],
    "PROMPT": os.environ.get("AZURE_PROMPT", "none"),
    "AUTHORITY": "https://login.microsoftonline.com/%s"
                 % (os.environ.get("AZURE_TENANT_ID", "")),
    "USERNAME_ATTRIBUTE": "mail",
    "GROUP_ATTRIBUTE": "roles",
}

if os.environ.get("AZURE_ROLES", "") != "":
    AZURE_AUTH["ROLES"] = json.loads(os.environ.get("AZURE_ROLES", ""))

LOGIN_URL = (
    "/azure_auth/login"
    if os.environ.get("AZURE_ENABLED", "false").lower() == "true"
    else "/login/"
)
LOGIN_REDIRECT_URL = "/"  # Or any other endpoint

AUTHENTICATION_BACKENDS = (
    ("azure_auth.backends.AzureBackend",)
    if os.environ.get("AZURE_ENABLED", "false").lower() == "true"
    else ("django.contrib.auth.backends.ModelBackend",)
)

IOMMI_MAIN_MENU = "skillsManager.urls.menu_declaration"
IOMMI_DEFAULT_STYLE = "skills"

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
