# Generated by Django 4.2.24 on 2025-10-29 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('skillsManager', '0001_initial'), ('skillsManager', '0002_alter_profile_active_until_alter_profilemeta_photo'), ('skillsManager', '0003_alter_profile_active_until_alter_profilemeta_photo'), ('skillsManager', '0004_alter_skill_related_skills'), ('skillsManager', '0005_alter_skill_related_skills'), ('skillsManager', '0006_alter_profileskillreference_remarks_and_more'), ('skillsManager', '0007_alter_certificate_description_and_more'), ('skillsManager', '0008_alter_profilecertificatereference_active_until'), ('skillsManager', '0009_alter_customer_active_until_and_more'), ('skillsManager', '0010_alter_customer_parent_customer'), ('skillsManager', '0011_remove_customer_parent_customer_and_more'), ('skillsManager', '0012_alter_customer_active_since_and_more'), ('skillsManager', '0013_customerlog_notice_projectlog_notice_and_more'), ('skillsManager', '0014_profile_profile_admins_alter_customer_active_since_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active_since', models.DateField(default=django.utils.timezone.now)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('parent_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillsManager.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('active_since', models.DateField(default=django.utils.timezone.now)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('profile_admins', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('active_since', models.DateField(default=django.utils.timezone.now)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_skills', models.ManyToManyField(blank=True, to='skillsManager.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSkillReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('favorite', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.certificatevendor')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.customer')),
                ('notice', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCertificateReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_since', models.DateField(default=django.utils.timezone.now)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.certificate')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.project')),
                ('notice', models.TextField(default='')),
            ],
        ),
    ]
