# Generated by Django 5.2.7 on 2025-10-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemeta',
            name='gender',
        ),
    ]
