# Generated by Django 5.2.7 on 2025-11-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0003_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemeta',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemeta',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemeta',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileProjectReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileProjectSkillReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_project_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profileprojectreference')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.skill')),
            ],
        ),
    ]
