# Generated by Django 5.2.7 on 2025-11-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0004_profilemeta_available_from_profilemeta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemeta',
            name='maturity_level',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
