# Generated by Django 5.2.7 on 2025-11-11 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0005_profilemeta_maturity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileprojectreference',
            name='active_since',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profileprojectreference',
            name='active_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileprojectreference',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
