# Generated by Django 5.2.7 on 2025-11-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0006_profileprojectreference_active_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemeta',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
