# Generated by Django 5.2.7 on 2025-11-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0007_alter_profilemeta_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
