# Generated by Django 5.2.7 on 2025-11-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0008_customer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
