# Generated by Django 5.2.7 on 2025-11-26 14:14

import skillsManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0009_customer_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecertificatereference',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=skillsManager.models.generate_certificate_filename),
        ),
    ]
