# Generated by Django 5.2.8 on 2025-12-01 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0010_profilecertificatereference_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='profilemeta',
            options={'verbose_name': 'Profile meta', 'verbose_name_plural': 'Profile metas'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=200, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active_since',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Active since'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active_until',
            field=models.DateField(blank=True, null=True, verbose_name='Active until'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='given_name',
            field=models.CharField(max_length=200, verbose_name='Given name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='profilemeta',
            name='available_from',
            field=models.DateField(blank=True, null=True, verbose_name='Available from'),
        ),
        migrations.AlterField(
            model_name='profilemeta',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='profilemeta',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profilemeta',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='profilemeta',
            name='maturity_level',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Maturity level'),
        ),
        migrations.AlterField(
            model_name='profilemeta',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='related_skills',
            field=models.ManyToManyField(blank=True, to='skillsManager.skill', verbose_name='Related skills'),
        ),
    ]
