# Generated by Django 5.2.8 on 2025-12-01 14:31

import django.db.models.deletion
import django.utils.timezone
import skillsManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0011_alter_education_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='certificatevendor',
            options={'verbose_name': 'Certificate vendor', 'verbose_name_plural': 'Certificate vendors'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customerlog',
            options={'verbose_name': 'Customer log', 'verbose_name_plural': 'Customer logs'},
        ),
        migrations.AlterModelOptions(
            name='profilecertificatereference',
            options={'verbose_name': 'Profile certificate reference', 'verbose_name_plural': 'Profile certificate references'},
        ),
        migrations.AlterModelOptions(
            name='profileprojectreference',
            options={'verbose_name': 'Profile project reference', 'verbose_name_plural': 'Profile project references'},
        ),
        migrations.AlterModelOptions(
            name='profileprojectskillreference',
            options={'verbose_name': 'Profile project skill reference', 'verbose_name_plural': 'Profile project skill references'},
        ),
        migrations.AlterModelOptions(
            name='profileskillreference',
            options={'verbose_name': 'Profile skill reference', 'verbose_name_plural': 'Profile skill references'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectlog',
            options={'verbose_name': 'Project log', 'verbose_name_plural': 'Project logs'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.certificatevendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='certificatevendor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='active_since',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Active since'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='active_until',
            field=models.DateField(blank=True, null=True, verbose_name='Active until'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='parent_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillsManager.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='notice',
            field=models.TextField(verbose_name='Notice'),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='language',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='profilecertificatereference',
            name='active_since',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Active since'),
        ),
        migrations.AlterField(
            model_name='profilecertificatereference',
            name='active_until',
            field=models.DateField(blank=True, null=True, verbose_name='Active until'),
        ),
        migrations.AlterField(
            model_name='profilecertificatereference',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.certificate', verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='profilecertificatereference',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=skillsManager.models.generate_certificate_filename, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='profilecertificatereference',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='profilemeta',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='profileprojectreference',
            name='active_since',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Active since'),
        ),
        migrations.AlterField(
            model_name='profileprojectreference',
            name='active_until',
            field=models.DateField(blank=True, null=True, verbose_name='Active until'),
        ),
        migrations.AlterField(
            model_name='profileprojectreference',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='profileprojectreference',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='profileprojectreference',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='profileprojectskillreference',
            name='profile_project_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profileprojectreference', verbose_name='Profile project reference'),
        ),
        migrations.AlterField(
            model_name='profileprojectskillreference',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.skill', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='profileskillreference',
            name='favorite',
            field=models.IntegerField(verbose_name='Favorite'),
        ),
        migrations.AlterField(
            model_name='profileskillreference',
            name='level',
            field=models.IntegerField(verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='profileskillreference',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='profileskillreference',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='profileskillreference',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.skill', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='active_since',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Active since'),
        ),
        migrations.AlterField(
            model_name='project',
            name='active_until',
            field=models.DateField(blank=True, null=True, verbose_name='Active until'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='notice',
            field=models.TextField(verbose_name='Notice'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.project', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.TextField(verbose_name='Template'),
        ),
    ]
