# Generated by Django 5.2.8 on 2025-12-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsManager', '0012_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsManager.project', verbose_name='Project'),
        ),
    ]
