# Generated by Django 5.2.8 on 2025-12-04 10:42

from django.db import migrations


def add_groups(apps, schema_editor):
    # noinspection PyPep8Naming
    Group = apps.get_model("auth", "Group")
    # noinspection PyPep8Naming
    Permission = apps.get_model("auth", "Permission")

    todos = [
        (
            "SkillsManager - Skills Manager",
            Permission.objects.filter(content_type__app_label="skillsManager", codename__endswith="_skill")
        ),
        (
            "SkillsManager - Certificates Manager",
            Permission.objects.filter(content_type__app_label="skillsManager", codename__regex="_certificate(vendor)?$")
        ),
        (
            "SkillsManager - Projects Manager",
            Permission.objects.filter(content_type__app_label="skillsManager",
                                      codename__regex="_(project|customer)(log)?$")
        ),
        (
            "SkillsManager - Templates Manager",
            Permission.objects.filter(content_type__app_label="skillsManager", codename__endswith="_template")
        ),
        (
            "SkillsManager - Readonly",
            Permission.objects.filter(content_type__app_label="skillsManager", codename__startswith="view")
        ),
        ("SkillsManager - Admins", Permission.objects.all())
    ]

    for todo in todos:
        skills_manager = Group()
        skills_manager.name = todo[0]
        skills_manager.save()
        for permission in todo[1]:
            skills_manager.permissions.add(permission)
        skills_manager.save()


class Migration(migrations.Migration):
    dependencies = [
        ('skillsManager', '0013_alter_projectlog_project'),
    ]

    operations = [
        migrations.RunPython(add_groups),
    ]
