# Generated by Django 5.2.8 on 2025-12-04 10:42

from django.db import migrations


def add_groups(apps, schema_editor):
    # noinspection PyPep8Naming
    Group = apps.get_model("auth", "Group")
    # noinspection PyPep8Naming
    Permission = apps.get_model("auth", "Permission")

    todos = [
        (
            "SkillsManager - Skills Manager",
            Permission.objects.filter(content_type__app_label="skillsManager", codename__endswith="_skillcategory")
        ),
        (
            "SkillsManager - Readonly",
            Permission.objects.filter(content_type__app_label="skillsManager", codename="view_skillcategory")
        ),

        (
            "SkillsManager - Admins",
            Permission.objects.filter(content_type__app_label="skillsManager", codename__endswith="_skillcategory")
        )
    ]

    for todo in todos:
        skills_manager = Group.objects.get(name=todo[0])
        for permission in todo[1]:
            skills_manager.permissions.add(permission)
        skills_manager.save()


def delete_groups(apps, schema_editor):
    # noinspection PyPep8Naming
    Group = apps.get_model("auth", "Group")
    # noinspection PyPep8Naming
    Permission = apps.get_model("auth", "Permission")

    todos = [
        (
            "SkillsManager - Skills Manager",
            Permission.objects.filter(content_type__app_label="skillsManager", codename__endswith="_skillcategory")
        ),
        (
            "SkillsManager - Readonly",
            Permission.objects.filter(content_type__app_label="skillsManager", codename="view_skillcategory")
        ),

        (
            "SkillsManager - Admins",
            Permission.objects.filter(content_type__app_label="skillsManager", codename__endswith="_skillcategory")
        )
    ]

    for todo in todos:
        skills_manager = Group.objects.get(name=todo[0])
        for permission in skills_manager.permissions.filter(codename__endswith="_skillcategory"):
            skills_manager.permissions.remove(permission)
        skills_manager.save()


class Migration(migrations.Migration):
    dependencies = [
        ('skillsManager', '0016_skillcategory_skill_category'),
    ]

    operations = [
        migrations.RunPython(add_groups, delete_groups),
    ]
