import os
from django.urls import path

from .views import (
    cv,
    profile,
    skill,
    certificate,
    skill_search,
    home,
    project,
    template,
    project_work,
)
from iommi.experimental.main_menu import MainMenu, M, EXTERNAL

menu_declaration = MainMenu(
    items=(
        dict(
            home=M(
                icon="home",
                view=home.HomePage().as_view(),
            ),
            cv=M(
                icon="print",
                view=cv.CVPage().as_view(),
            ),
            skill_search=M(
                icon="search",
                view=skill_search.SkillSearchPage().as_view(),
            ),
            profiles=M(
                icon="users",
                view=profile.ProfileView().as_view(),
                paths=[
                    path(
                        "<int:pk>/",
                        profile.ProfileEdit().as_view(),
                        name="profile-view",
                    ),
                    path(
                        "<int:pk>/edit/",
                        profile.ProfileEdit().as_view(),
                        name="profile-edit",
                    ),
                    path(
                        "<int:pk>/delete/",
                        profile.profile_delete.as_view(),
                        name="profile-delete",
                    ),
                    path(
                        "<int:profile_pk>/work/",
                        project_work.ProjectWorkView().as_view(),
                        name="projectwork-list",
                    ),
                    path(
                        "<int:profile_pk>/work/<int:pk>/",
                        project_work.ProjectWorkEdit().as_view(),
                        name="projectwork-view",
                    ),
                    path(
                        "<int:profile_pk>/work/<int:pk>/edit/",
                        project_work.ProjectWorkEdit().as_view(),
                        name="projectwork-edit",
                    ),
                    path(
                        "<int:profile_pk>/work/<int:pk>/delete/",
                        project_work.project_work_delete.as_view(),
                        name="projectwork-delete",
                    ),
                ],
            ),
            skills=M(
                icon="check",
                view=skill.SkillView().as_view(),
                paths=[
                    path("<int:pk>/", skill.skill_edit.as_view(), name="skill-view"),
                    path(
                        "<int:pk>/edit/",
                        skill.skill_edit.as_view(),
                        name="skill-edit",
                    ),
                    path(
                        "<int:pk>/delete/",
                        skill.skill_delete.as_view(),
                        name="skill-delete",
                    ),
                ],
            ),
            certificates=M(
                icon="certificate",
                view=certificate.VendorView().as_view(),
                paths=[
                    path(
                        "<int:pk>/",
                        certificate.VendorEdit().as_view(),
                        name="vendor-view",
                    ),
                    path(
                        "<int:pk>/edit/",
                        certificate.VendorEdit().as_view(),
                        name="vendor-edit",
                    ),
                    path(
                        "<int:pk>/delete/",
                        certificate.vendor_delete.as_view(),
                        name="vendor-delete",
                    ),
                ],
            ),
            projects=M(
                icon="book",
                view=project.CustomerView().as_view(),
                paths=[
                    path(
                        "<int:pk>/",
                        project.CustomerEdit().as_view,
                        name="customer-view",
                    ),
                    path(
                        "<int:pk>/edit/",
                        project.CustomerEdit().as_view(),
                        name="customer-edit",
                    ),
                    path(
                        "<int:pk>/delete/",
                        project.customer_delete.as_view(),
                        name="customer-delete",
                    ),
                ],
            ),
            templates=M(
                icon="file",
                view=template.TemplateView().as_view(),
                paths=[
                    path(
                        "<int:pk>/",
                        template.template_edit.as_view(),
                        name="template-view",
                    ),
                    path(
                        "<int:pk>/edit/",
                        template.template_edit.as_view(),
                        name="template-edit",
                    ),
                    path(
                        "<int:pk>/delete/",
                        template.template_delete.as_view(),
                        name="template-delete",
                    ),
                ],
            ),
        )
        | (
            dict()
            if os.environ.get("AZURE_ENABLED", "false").lower() == "true"
            else dict(
                change_password=M(icon="key", view=EXTERNAL, url="/change_password")
            )
        )
        | dict(logout=M(icon="sign-out", view=EXTERNAL, url="/logout"))
    )
)

urlpatterns = menu_declaration.urlpatterns()
