import os

from django.urls import path
from iommi.main_menu import MainMenu, M, EXTERNAL

from .views import (
    cv,
    profile,
    skill,
    skill_search,
    home,
    project,
    template,
    certificate,
)

menu_declaration = MainMenu(
    items=(
            dict(
                home=M(
                    icon="home",
                    view=home.HomePage().as_view(),
                ),
                cv=M(
                    icon="print",
                    view=cv.CVPage().as_view(),
                ),
                skill_search=M(
                    icon="search",
                    view=skill_search.SkillSearchPage().as_view(),
                ),
                profiles=M(
                    icon="users",
                    view=profile.ProfileView().as_view(),
                    paths=[
                        path(
                            "<int:pk>/",
                            profile.ProfileEdit().as_view(),
                            name="profile-view",
                        ),
                        path(
                            "<int:pk>/edit/",
                            profile.ProfileEdit().as_view(),
                            name="profile-edit",
                        ),
                        path(
                            "<int:pk>/delete/",
                            profile.profile_delete.as_view(),
                            name="profile-delete",
                        ),
                        path(
                            "<int:profile_pk>/work/",
                            profile.project_work.ProjectWorkView().as_view(),
                            name="projectwork-list",
                        ),
                        path(
                            "<int:profile_pk>/work/<int:pk>/",
                            profile.project_work.ProjectWorkEdit().as_view(),
                            name="projectwork-view",
                        ),
                        path(
                            "<int:profile_pk>/work/<int:pk>/edit/",
                            profile.project_work.ProjectWorkEdit().as_view(),
                            name="projectwork-edit",
                        ),
                        path(
                            "<int:profile_pk>/work/<int:pk>/delete/",
                            profile.project_work.project_work_delete.as_view(),
                            name="projectwork-delete",
                        ),
                        path(
                            "<int:profile_pk>/certificates/",
                            profile.certificate.ProfileCertificateView().as_view(),
                            name="profilecertificates-list",
                        ),
                        path(
                            "<int:profile_pk>/certificates/<int:pk>/",
                            profile.certificate.ProfileCertificateEdit().as_view(),
                            name="profilecertificates-view",
                        ),
                        path(
                            "<int:profile_pk>/certificates/<int:pk>/edit/",
                            profile.certificate.ProfileCertificateEdit().as_view(),
                            name="profilecertificates-edit",
                        ),
                        path(
                            "<int:profile_pk>/certificates/<int:pk>/delete/",
                            profile.certificate.profile_certificate_delete.as_view(),
                            name="profilecertificates-delete",
                        ),
                        path(
                            "<int:profile_pk>/skills/",
                            profile.skill.ProfileSkillView().as_view(),
                            name="profileskills-list",
                        ),
                        path(
                            "<int:profile_pk>/skills/<int:pk>/",
                            profile.skill.ProfileSkillEdit().as_view(),
                            name="profileskills-view",
                        ),
                        path(
                            "<int:profile_pk>/skills/<int:pk>/edit/",
                            profile.skill.ProfileSkillEdit().as_view(),
                            name="profileskills-edit",
                        ),
                        path(
                            "<int:profile_pk>/skills/<int:pk>/delete/",
                            profile.skill.profile_skill_delete.as_view(),
                            name="profileskills-delete",
                        ),
                    ],
                ),
                skills=M(
                    icon="check",
                    view=skill.SkillView().as_view(),
                    paths=[
                        path("<int:pk>/", skill.SkillEdit().as_view(), name="skill-view"),
                        path(
                            "<int:pk>/edit/",
                            skill.SkillEdit().as_view(),
                            name="skill-edit",
                        ),
                        path(
                            "<int:pk>/delete/",
                            skill.skill_delete.as_view(),
                            name="skill-delete",
                        ),
                    ],
                ),
                certificates=M(
                    icon="certificate",
                    view=certificate.VendorView().as_view(),
                    paths=[
                        path(
                            "<int:pk>/",
                            certificate.VendorEdit().as_view(),
                            name="vendor-view",
                        ),
                        path(
                            "<int:pk>/edit/",
                            certificate.VendorEdit().as_view(),
                            name="vendor-edit",
                        ),
                        path(
                            "<int:pk>/delete/",
                            certificate.vendor_delete.as_view(),
                            name="vendor-delete",
                        ),
                    ],
                ),
                projects=M(
                    icon="book",
                    view=project.CustomerView().as_view(),
                    paths=[
                        path(
                            "<int:pk>/",
                            project.CustomerEdit().as_view,
                            name="customer-view",
                        ),
                        path(
                            "<int:pk>/edit/",
                            project.CustomerEdit().as_view(),
                            name="customer-edit",
                        ),
                        path(
                            "<int:pk>/delete/",
                            project.customer_delete.as_view(),
                            name="customer-delete",
                        ),
                    ],
                ),
                templates=M(
                    icon="file",
                    view=template.TemplateView().as_view(),
                    paths=[
                        path(
                            "<int:pk>/",
                            template.TemplateEdit().as_view(),
                            name="template-view",
                        ),
                        path(
                            "<int:pk>/edit/",
                            template.TemplateEdit().as_view(),
                            name="template-edit",
                        ),
                        path(
                            "<int:pk>/delete/",
                            template.template_delete.as_view(),
                            name="template-delete",
                        ),
                    ],
                ),
            )
            | (
                dict()
                if os.environ.get("AZURE_ENABLED", "false").lower() == "true"
                else dict(
                    change_password=M(icon="key", view=EXTERNAL, url="/change_password")
                )
            )
            | dict(logout=M(icon="sign-out", view=EXTERNAL, url="/logout"))
    )
)

urlpatterns = menu_declaration.urlpatterns()
